# Generated by Django 5.1.7 on 2025-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_groupexpense_individualexpense_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='member5',
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='members',
            field=models.ManyToManyField(related_name='group_expenses', to='myapp.member'),
        ),
    ]
